config/routes.rb
Chrissybmspt::Application.routes.draw do

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  get "patient_info/visits"

  get "patient_info/profile"

  get "patient_info/progress"

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :patients

  authenticated :user do
    root :to => 'home#index'
  end

  get "about" => "home#about"
  get "new_patients" => "home#new_patients"
  get "services" => "home#services"
  get "testimonials" => "home#testimonials"
  get "contact_success" => "contact#success"

  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :patient
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :parents_names, :email, :phone, :childs_name, :city, :concern, :body

  validates :parents_names, :childs_name,  :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :goals
  has_many :visits
  belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :patients
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :patient
  #t.datetime "meeting_start_time"
  #t.datetime "meeting_end_time"
  #t.string   "notes"
  #t.string   "location"
  #t.datetime "created_at",         :null => false
  #t.datetime "updated_at",         :null => false

  def short_description
    "#{self.meeting_start_time.to_s} to #{self.meeting_end_time.to_s}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #http_basic_authenticate_with :name => "chrissy", :password => "happy"
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(contact_success_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if User.all.size > 0
      @users = User.all
      else
      @users = nil
    end
  end

  def about

  end

  def services
     @services = Service.all
  end

  def new_patients

  end

end

app/controllers/patient_info_controller.rb
class PatientInfoController < ApplicationController
  layout 'patient_info.html'
  before_filter :authenticate_user!
  before_filter :find_user
  def visits

  end

  def profile

  end

  def progress

  end

  def find_user
    @user = current_user
    @patient = @user.patients.first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patient_info_helper.rb
module PatientInfoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/visits/_visit_form.html.haml
= semantic_form_for [:admin, @visit] do |f|
  = f.input :patient, collection: Patient.all
  = f.input :meeting_start_time
  = f.input :meeting_end_time
  = f.input :location
  = f.input :notes, as: :text, :input_html => {:class => :ckeditor}
  = f.submit

app/views/contact/new.html.haml
- title "Contact Us"

- content_for :sidebar do
  %p &nbsp;

%p
  You may reach us via phone or email. If you would prefer, please fill out the form below
  to let us know your preferred method of contact, as well as a good time to reach you.
  We look forward to talking with you soon!

= simple_form_for @message, :html => {:class => 'form-horizontal' }, :url => contact_path do |form|
  %fieldset
    = form.input :parents_names, input_html: {class: "span6"}, :label => "Your Name"
    = form.input :email, input_html: {class: "span6"}
    = form.input :phone, input_html: {class: "span6"}
    = form.input :childs_name, input_html: {class: "span6"}, :label => "Your Child's Name"
    = form.input :concern, input_html: {class: "span6"}
    = form.input :city, input_html: {class: "span6"}, :label => "Your Zip Code or City"
    = form.input :body, as: :text, input_html: {class: "span6", rows: "5"}, :label => "Any Additional Comments (best time to reach you/ preferred method of contact...)", :label => "Any other notes"
  .form-actions
    = form.button :submit, class: 'btn-primary'

app/views/contact/success.html.haml
- title "Thank you!"

- content_for :sidebar do
  %p
    = image_tag "ChrissyPics/AnnieOnBall.jpg"
  %p
    = image_tag "ChrissyPics/AnnieOnRoady.jpg"

%p
  Thank you for contacting me. I'm excited to talk to you.

%p I am a chicken -- spicy and sweet.

app/views/home/about.html.haml
- title "About Us"

- content_for :wide_open do

  .LayoutBreakAfter
    .ArticleGrid-1
      %p

        = image_tag "ChrissyPics/AnnieHappy.jpg"
        = image_tag "ChrissyPics/triplets.jpg"
        = image_tag "ChrissyPics/ToddlerWalking.jpg"


    .ArticleGrid-2-4
      %h2 Why home visits?

      %p
        Sessions are held in the child's home for the same cost one would pay for
        an office visit to see a Physical Therapist at a clinic or hospital.
        In addition to being more convenient for busy families, we find that our
        clients achieve greater success when treated in their home, using familiar toys.
        Working in the home environment also helps parents and caregivers learn activities
        and exercises more easily to do with their child in between treatment sessions.

      %p
        We use Play based therapy sessions, which sets children up for success in an environment
        that is fun, nurturing and safe. Working together in your child's home environment also
        helps us to better understand your family's and your child's routines so that
        we may best coach you in activities and exercises that will help your child and meet your goals.

      %h2 How long is a treatment session?

      %p
        The length of a session is typically about an hour. The frequency of treatment is tailored
        to the needs of each child. Some children are seen once a week - others are seen every other
        two weeks. Again, this depends upon the needs of the child. In situations when children
        are seen post-surgically, sessions are scheduled more frequently.

      %h2 How involved are parents in the treatment sessions?

      %p
        Therapy is most successful for the child when parents are actively involved in the treatment sessions.
        Pediatric Physical Therapists are highly trained and skilled in working with infants, toddlers and children
        but we only see the child once a week and so much of our focus is on teaching the parents strategies
        and activities to work on with their child in between sessions, in the context of a child's
        daily routine and activities.

  .LayoutBreakAfter
    .ArticleGrid-1
      &nbsp;
    .ArticleGrid-2-4
      %h2 About Us

  .LayoutBreakAfter
    .ArticleGrid-1
      %p
        = image_tag "ChrissyPics/ChrissyDavidLookingAtEachOther.jpg"
    .ArticleGrid-2-4
      %h3 Chrissy

      %p
        Based in Alexandria, VA, Chrissy treats infants and children in Alexandria, Arlington, Springfield, Annandale and Falls Church.

        For the past 12 years, Chrissy has been a Pediatric Physical Therapist. A mom of four children, she loves working with
        children as well as their parents, and particularly enjoys helping them problem
        solve the best ways to overcome their individual challenges.
      %p
        Chrissy is adept at meeting the individual
        need of each child with a unique treatment approach, having been highly trained in a wide variety of
        techniques. Specialized training includes Neurodevelopmental Treatment (NDT), including specialized
        treatment of infants and preemies, facilitation of play based therapy incorporating sensory strategies,
        Kinesiotaping, NMES (Neuromuscular Electric Muscle
        Stimulation) and FES (Functional Electrical Muscle Stimulation) for
        children. She is also highly trained in fitting children for a variety
        of pediatric shoe inserts, orthotics and DAFOs. She is also very experienced in helping families make practical
        choices for their children regarding adaptive equipment.
        Originally from Massachusetts, Chrissy graduated
        from Boston University's Sargent College of Allied Health Professions with a Master of Science in Physical
        Therapy.
      %p
        Over the course of her career, Chrissy has had the privilege of working in a
        variety of specialized pediatric settings, including Children's
        Hospitals, Early Intervention, Schools, and Private Practice.
      %p
        In her free time, she delights in playing with her children, coaching
        soccer, cooking a delicious meal, or tackling the latest WOD at
        CrossFit Adaptation or at CrossFit Falls Church.

app/views/home/index.html.haml
- content_for :topbar do
  #wrapper
    #slider_wrapper
      #slider
        = image_tag "splash/PTPN_Logo_Banner.jpg"
        = image_tag "splash/ChrissyBallBanner.jpg"

  :javascript
    $(window).load(function() {
        $('#slider').nivoSlider();
    });

/ %h1.tk-lint-mccree Welcome
%h1 Welcome
/%h1.tk-swister-regular Welcome
/%h1.tk-proxima-nova Welcome
/%h1.tk-nimbus-sans Welcome
/%h1.tk-ff-prater-script-web Welcome

/ FF Prater Script Web


- content_for :sidebar do
  = image_tag "ChrissyAndAnne.jpg"

%p
  Chrissy Booher is a Pediatric Physical Therapist who provides in-home Physical Therapy Evaluation and Treatments
  to infants and children in Northern Virginia.
  Therapy is play based, yet guided by research driven principles as well as a
  thorough understanding of anatomy, human movement and development.

%p Thanks for visiting, and we look forward to talking with you soon!

app/views/home/new_patients.html.haml
- title "New Patients"

- content_for :sidebar do
  %p
    = image_tag "ChrissyPics/ChrissyDavidLookingAtEachOther.jpg"

%h2 What happens during my initial visit?

%p
  After initial contact via phone or email with the parent, we will schedule a visit to complete your
  child's evaluation at your home. If there are reports available from the hospital, appointments with
  other therapists, doctors or other specialists your child has seen, we may request a review of that information.

%p You will need to obtain a prescription from your child's pediatrician prior to the first appointment and fax it to us at 888.750.4126 or have it available at the evaluation.

%p
  We ask that you complete a form to complete prior to the evaluation. We will email this to you after we schedule your child's evaluation.
  This will help provide some very helpful information and will allow us to maximize the use of our time with your child.

%p At the evaluation, we will conduct an assessment process that looks like play. Children often do not realize that they are being evaluated.
%p The first sessions(s) are designed to assess your child's level of functioning in both gross and fine motor skills, sensory processing, daily living and play skills, and to determine factors that may interfere with age appropriate skill acquisition. Generally the sessions are about 1 hour and combine structured and unstructured activities.

%p You are encouraged to be actively involved in your child's evaluation and subsequent sessions. You know your child best and issues of separation can be minimized.

%p Our goal is to help you and your child feel as comfortable and playful as possible. While we understand that the process can be stressful, we do our best to minimize stress and facilitate open communication.

app/views/home/services.html.haml
- title "Physical Therapy Services"

- content_for :sidebar do

  %p
    = image_tag "ChrissyPics/AnnieOnRoady.jpg"

  %p
    = image_tag "ChrissyPics/ChrissyByCouch.jpg"

%p
  We provide a full range of in-home Pediatric Physical Therapy Evaluation and
  Treatment for infants and children, from birth to 18 years of age. We serve families in Arlington, Falls Church, Alexandria, Fairfax, and other select cities in the immediate area.

%p Some of the diagnoses we treat include:

%ul
  %li Torticollis
  %li Prematurity
  %li Delayed Gross Motor Skills
  %li Hypotonia (Low Muscle tone)
  %li Hypertonia
  %li Cerebral Palsy
  %li Genetic Disorders
  %li Spina Bifida
  %li Congenital Toe Walking
  %li Developmental Delay

%p
  We also offer Parent Education, including developmental education coaching and
  consultations for parents of newborns to those six months of age.

%h3 Torticollis

%p Is a condition  that literally means "twisted neck. " It is derived from the Latin terms Torta, meaning twisted and Collum, meaning neck.

%p Infants with Torticollis have a strong preference for looking toward one side. In addition, they may have a flat spot on the back of their head. Torticollis may be present from birth or may develop in the first few months after birth.

%p Torticollis can be caused by several different underlying conditions. The most common is Congenital Muscular Torticollis (from birth, caused by muscular tightness). Torticollis may also be caused by vision problems (Ocular Torticollis), by bony abnormalities in the spine, or by neurological balance problems (Benign Paroxysmal Torticollis).

%h3 Developmental Delays:

%p Developmental Delay is a "catch all" phrase to describe many different conditions that may cause an infant or toddler to have difficulty with Motor Milestones such as sitting, crawling, pulling to stand or walking.

%h3 Hypotonia

%p Hypotonia (or low muscle tone) is a neurological condition. Normally, even when relaxed, muscles have a small amount of contraction or resistance that give them a springy feel and provide a small amount of resistance to passive movement. Low muscle tone is not the same thing as muscle weakness, although the two can co-exist.

%p Infants with low tone may show difficulties with head control and/ or delays in the acquisition of gross motor skills (tummy time, rolling, propping on forearms, sitting up, standing or walking). They often have a hard time with tummy time or with lifting their head for a sustained period of time. There are varying degrees of low tone and there are many causes for it. Parents of children with low tone often describe their children as feeling "floppy."

%h3 Toe-Walking

%p Toe-Walking is an abnormal gait pattern that, if untreated, can cause joint contractures at the ankles and bony anomalies over time. There are many causes for Toe- Walking including Hypertonia (increased muscle tone), Sensory Processing Disorder, Hypotonia (low muscle tone), and Congenital (from birth) tightness of the heel cord, as well as others.  Physical Therapy can help improve a child's range of motion and strength and greatly improve their balance as well as their ability to walk. Therapy can also decrease the need for other, more invasive treatment techniques.

app/views/home/testimonials.html.haml
- title "What People are Saying"


%h2 Julia & Andrew from Arlington

%blockquote
  %p We recommend Chrissy highly and without hesitation.  We met her in 2010, when our pediatrician told us that our 8-week old son needed to start physical therapy.  As first time parents, we were incredibly fearful.  Chrissy eased our fears and concerns by taking the time to educate us on our son’s condition, what to expect from her as his physical therapist, and what steps we would take together to help him get better.  In 2011, we learned that our second son required physical therapy, also starting at 8 weeks old.  Both of our sons have thrived under her high quality of care and over the past two and a half years, she has celebrated each of their milestones with us - both big and small.  She truly cares about our sons and we are so appreciative for everything that she has done for our family.

%h2 Lindsay & Chad from Fairfax

%blockquote
  %p Chrissy is truly great.  She put my mind at ease and answered all of my many questions during the initial meeting.  We have seen incredible progress in our son since we started working with Chrissy.  She makes sure we understand the next steps, goals, and what to work on from week to week.  She is great with our son and encourages him and us.  She is very responsive and genuinely cares about our son's progress.  She wrote a very comprehensive report for his pediatrician as well.
  %p We are very lucky to have found her!

app/views/layouts/_footer.html.haml
/ = image_tag "white_hands.png"
.LayoutGrid-1-4.LayoutSlimGrid-1-2.LinkInvert.LinkStrong
  .LayoutCellSides.LayoutCellBottom.LinkInvert
    %p.SiteFooterRow.TextSmall.TextInvert
      %table.TextSmall.TextInvert{style: "width:80%; height:55px;"}
        %tr
          %td Chrissy Booher, MS, PT (based in Alexandria)
          %td chrissy@ptpnova.com
          %td 571.212.6145

.LayoutGridBreak
  .LayoutCellSides
    %hr
.LayoutGrid-1-4.LayoutSlimGrid-1-2.LinkInvert.LinkStrong
  .LayoutCellSides.LayoutCellBottom.LinkInvert
    %p.SiteFooterRow.TextSmall.TextInvert
      Copyright © 2012 Pediatric Therapy Partners of NOVA.  All rights reserved.

app/views/layouts/_navigation.html.haml
.SiteHeaderTitle
  = link_to "PEDIATRIC THERAPY PARTNERS OF NOVA", "/", class: "LinkInvert"
.SiteHeaderBarItem
  =link_to 'About', about_path
.SiteHeaderBarItem
  =link_to 'Services', services_path
.SiteHeaderBarItem
  =link_to 'New Patients', new_patients_path
.SiteHeaderBarItem
  =link_to 'Contact', contact_path
.SiteHeaderBarItem
  =link_to 'Testimonials', testimonials_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    / start of new things
    %meta{:charset => "utf-8"}/
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}/
    %title= content_for?(:title) ? yield(:title) : "Pediatric Therapy Partners of NOVA"
    %meta{:content => "Personal pediatric physical therapy practice that makes children stronger throughout northern virginia. Our therapists specialize in pediatric care and have a minimum of 15 years of experience.", :name => "description"}
    %meta{:content => "pediatric, physical therapy, northern virginia", :name => "keywords"}
    %meta{:content => "Tim Booher", :name => "author"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
    %script{:src => "//use.typekit.net/wut2wet.js", :type => "text/javascript"}
    :javascript
      try{Typekit.load();}catch(e){}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body.text
    #ArticleGrid
      #SiteHeader.TextSmall
        / = link_to "", "/", class: "SiteHeaderHome"
        #SiteHeaderBar
          = render 'layouts/navigation'
      #Title
        - if content_for?(:title)
          .LayoutBreakAfter.title
            .ArticleGrid-1
              &nbsp;
            .ArticleGrid-2-4
              %h1= yield(:title)
            - if content_for?(:subtitle)
              %p.description= yield(:subtitle)
      #main_content.text
        - if content_for?(:topbar)
          .LayoutBreakAfter.topbar
            = yield(:topbar)
        .LayoutBreakAfter
          .ArticleGrid-1
            - if content_for?(:sidebar)
              = yield(:sidebar)
            - else
              %p &nbsp;
          .ArticleGrid-2-4
            .mainContent
              = yield
        - if content_for?(:wide_open)
          .LayoutBreakAfter
            =yield(:wide_open)
      #SiteFooter
        = render 'layouts/footer'

%script
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40651058-1', 'ptpnova.com');
  ga('send', 'pageview');

app/views/patient_info/profile.html.haml
- title "Profile"

%p here we show the patient's diagnosis, consents, etc . . .

app/views/patient_info/progress.html.haml
- title "progress"

%p
  Welcome,
  = @user.name

- unless @patient.nil?
  %h2= "Progress for #{@patient.name}"

  %h3 Goals
  - @patient.goals.each do |goal|
    %h4
      Date:
      = goal.goal_date
    %h4 Description
    = goal.description

  %h3 Visits
  - @patient.visits.each do |visit|
    %h4= visit.short_description
    %h4 Notes
    = visit.notes.html_safe

app/views/patient_info/visits.html.haml
- title "visits"

- @patient.visits.each do |visit|
  %h4= visit.short_description
  %h4 Notes
  = visit.notes.html_safe

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}